### ISSUE TITLE
If you have time, please add 1.21.4 support

### ISSUE THREAD

**Issue by werra11** [RodneyMKay/F3NPerm#13]
As the title said, please add 1.21.4 support.
The plugin does seem to load but the few commands are not available and F3 + N shows no permissions.

**Comment by TobyMinceraft** [comment]
Can confirm, currently does not work in version 1.21.4, using Paper.
`[20:12:47] [Server thread/WARN]: [F3NPerm] Task #39 for F3NPerm v3.5 generated an exception
nexus.slime.f3nperm.provider.ProviderException: Could not send packet!
    at F3NPerm-3.5.jar/nexus.slime.f3nperm.provider.ReflectionProvider_1_20_5.sendPacket(ReflectionProvider_1_20_5.java:46) ~[F3NPerm-3.5.jar:?]
    at F3NPerm-3.5.jar/nexus.slime.f3nperm.provider.NettyProvider.update(NettyProvider.java:36) ~[F3NPerm-3.5.jar:?]
    at F3NPerm-3.5.jar/nexus.slime.f3nperm.F3NPermListener.lambda$onJoin$0(F3NPermListener.java:24) ~[F3NPerm-3.5.jar:?]
    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1805) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1666) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1331) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
    at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: nexus.slime.f3nperm.reflection.ReflectionException: Could not access field e on java.lang.Number
    at F3NPerm-3.5.jar/nexus.slime.f3nperm.reflection.Reflections.getPrivate(Reflections.java:203) ~[F3NPerm-3.5.jar:?]
    at F3NPerm-3.5.jar/nexus.slime.f3nperm.provider.ReflectionProvider_1_20_5.getNetworkManager(ReflectionProvider_1_20_5.java:26) ~[F3NPerm-3.5.jar:?]
    at F3NPerm-3.5.jar/nexus.slime.f3nperm.provider.ReflectionProvider_1_20_5.sendPacket(ReflectionProvider_1_20_5.java:41) ~[F3NPerm-3.5.jar:?]
    ... 9 more
Caused by: java.lang.NoSuchFieldException: e
    at java.base/java.lang.Class.getDeclaredField(Class.java:2782) ~[?:?]
    at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
    at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
    at F3NPerm-3.5.jar/nexus.slime.f3nperm.reflection.Reflections.getPrivate(Reflections.java:199) ~[F3NPerm-3.5.jar:?]
    at F3NPerm-3.5.jar/nexus.slime.f3nperm.provider.ReflectionProvider_1_20_5.getNetworkManager(ReflectionProvider_1_20_5.java:26) ~[F3NPerm-3.5.jar:?]
    at F3NPerm-3.5.jar/nexus.slime.f3nperm.provider.ReflectionProvider_1_20_5.sendPacket(ReflectionProvider_1_20_5.java:41) ~[F3NPerm-3.5.jar:?]
    ... 9 more`
